POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "yeob32@gmail.com",
  "password": "1234",
  "platform": "desktop"
}

> {%
client.global.set("Authorization", response.headers.valueOf("Set-Cookie").split(";")[0].split("=")[1]);
client.log("쿠키: "+client.global.get("Authorization"));
%}

###

GET http://localhost:8080/api/member
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{Authorization}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET http://localhost:8080/api/posts
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{Authorization}}

###

GET http://localhost:8080/api/auth/token
Content-Type: application/json
Authorization: Bearer {{Authorization}}
