POST http://localhost:8080/api/login
Content-Type: application/json

{"email":"yeob32@gmail.com","password":"1234", "platform": "desktop"}

###

GET http://localhost:8080/api/member
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5ZW9iMzJAZ21haWwuY29tIiwic2NvcGVzIjpbXSwiaXNzIjoieWVvYjMyIiwiaWF0IjoxNjAwNjE0MTY1LCJleHAiOjE2MDA2MTc3NjV9.tk0rYwinfzqny20u-KxeDOtQnhcrINN96vrij2oNhYyZghbeHKZe4v0v1ZBm2JEvxsrRg2xSfnI5P5lR1EHKJw

###

GET http://localhost:8080/api/posts
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5ZW9iMzJAZ21haWwuY29tIiwic2NvcGVzIjpbXSwiaXNzIjoieWVvYjMyIiwiaWF0IjoxNjAwNjE0MTY1LCJleHAiOjE2MDA2MTc3NjV9.tk0rYwinfzqny20u-KxeDOtQnhcrINN96vrij2oNhYyZghbeHKZe4v0v1ZBm2JEvxsrRg2xSfnI5P5lR1EHKJw

###
