GET http://localhost:8080/api/v1/person/master
Accept: application/json

###

GET http://localhost:8080/api/v1/person/slave
Accept: application/json

###

PUT http://localhost:8080/api/v1/person/master
Content-Type: application/json

{}

###

PUT http://localhost:8080/api/v1/person/slave
Content-Type: application/json

{}

###
